version: 0.0
os: linux

files:
  - source: /build.zip 
    destination: /home/ec2-user/

hooks:
  BeforeInstall:
   
   - location: scripts/extract_artifact.sh   # New script to extract the .zip
      timeout: 300
      runas: root
      
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/deploy_frontend.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_docker.sh
      timeout: 300
      runas: root
