version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies for CodeBuild..."
      - sudo yum update -y
      - sudo yum install -y git 
      - git --version
      - cd $HOME
      - ls -lrta
      - node --version
      - npm --version
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
      - bash $CODEBUILD_SRC_DIR/codebuild_nvm_wrapper.sh

  pre_build:
    commands:
      - echo "Cloning repository..."
      - git clone https://github.com/mohanish619/fronted.git
      - cd fronted/frontend/
      - echo "VITE_API_URL=/api" > .env
      - npm install

  build:
    commands:
      - echo "Building the React app..."
      - npm run build
      - echo "Building Docker image..."
      - docker build -t frontend-image .

  post_build:
    commands:
      - echo "Saving Docker image as tarball..."
      - docker save frontend-image > frontend_image.tar

artifacts:
  files:
    - frontend_image.tar
    - appspec.yml
    - scripts/**
