version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Use Node.js runtime
    commands:
      - echo "Installing Docker..."
      - npm --version
      - yum update -y
      - yum install -y docker
      - service docker start
      - docker --version

  pre_build:
    commands:
      - echo "Cloning the repository..."
      - git clone https://github.com/mohanish619/fronted.git
      - cd fronted
      - echo "Setting up Node.js environment..."
      - npm install

  build:
    commands:
      - echo "Building the React app..."
      - npm run build
      - echo "Building Docker image..."
      - docker build -t frontend-image .

  post_build:
    commands:
      - echo "Saving Docker image as tarball..."
      - docker save frontend-image > frontend_image.tar

artifacts:
  files:
    - frontend_image.tar
