version: 0.2

phases:
  install:
    
    commands:
      - echo "Installing Docker..."
      - yum update -y
      - yum install -y docker
      

  pre_build:
    commands:
      - echo "Cloning the repository..."
      - cd /codebuild/output/src4240265109/src/github.com/mohanish619/fronted
      - echo "Installing Node.js dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the React app..."
      - npm run build
      - echo "Building Docker image..."
      - docker build -t frontend-image .

  post_build:
    commands:
      - echo "Saving Docker image as tarball..."
      - docker save frontend-image > frontend_image.tar

artifacts:
  files:
    - frontend_image.tar
    - appspec.yml
    - scripts/**
