version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies for CodeBuild..."
      - sudo yum update -y
      - sudo yum install -y git
      - git --version

  pre_build:
    commands:
    - echo "Cloning repository..."
    - git clone https://github.com/mohanish619/fronted.git
    - cd fronted/frontend/
    - echo "VITE_API_URL=/api" > .env
    - npm install
    - echo "Listing contents of frontend/..."
    - ls  # This will show the structure inside frontend/

  build:
    commands:
    - echo "Building the React app..."
    - npm run build
    - echo "Listing contents of frontend/build..."
    - ls dist   # Verify if the build directory exists
    - npm run build || exit 1  # Ensure build fails loudly if there's an error
    - echo "Building Docker image..."
    - docker build -t frontend-image .


  post_build:
    commands:
      - echo "Saving Docker image as tarball..."
      - docker save frontend-image > frontend_image.tar

artifacts:
  files:
    - frontend_image.tar
    - appspec.yml
    - scripts/**
